name: "Build APK"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Buildozer global directory
        uses: actions/cache@v4
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}

      - name: Cache Buildozer build directory
        uses: actions/cache@v4
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ github.sha }}-${{ hashFiles('buildozer.spec') }}

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        env:
          # Set JAVA_HOME to the JDK path that exists inside the action's Docker image
          JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
          APP_ANDROID_ACCEPT_SDK_LICENSE: "1"
        with:
          command: buildozer -v android debug --log-level 2
          buildozer_version: stable

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: datefacts-apk
          path: ${{ steps.buildozer.outputs.filename }}
